//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cloud_Background.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuxDeviceActions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AuxDeviceActions()
        {
            this.HistoricDevices = new HashSet<HistoricDevices>();
        }
    
        public int IDAuxDeviceAction { get; set; }
        public string DeviceAction { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoricDevices> HistoricDevices { get; set; }
    }
}
