//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cloud_Background.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Devices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Devices()
        {
            this.HistoricData = new HashSet<HistoricData>();
            this.HistoricDevices = new HashSet<HistoricDevices>();
        }
    
        public int IDDevice { get; set; }
        public string DeviceName { get; set; }
        public int IDAuxDeviceType { get; set; }
        public bool DeviceEnabled { get; set; }
        public bool DeviceConnected { get; set; }
        public bool DeviceNeedLogin { get; set; }
        public int DeviceInterval { get; set; }
        public System.DateTime DeviceCreationDate { get; set; }
        public string DeviceUsername { get; set; }
        public string DevicePassword { get; set; }
        public int IDDeviceProtocol { get; set; }
        public string DeviceAux { get; set; }
    
        public virtual AuxDeviceProtocols AuxDeviceProtocols { get; set; }
        public virtual AuxDeviceType AuxDeviceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoricData> HistoricData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoricDevices> HistoricDevices { get; set; }
    }
}
