//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cloud_Background.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricData
    {
        public int IDHistoricData { get; set; }
        public int IDDevice { get; set; }
        public System.DateTime HistDataDate { get; set; }
        public string HistDataValue { get; set; }
        public int IDDataType { get; set; }
        public bool HistDataToDevice { get; set; }
        public bool HistDataAck { get; set; }
        public string HistDataAux { get; set; }
    
        public virtual AuxDataType AuxDataType { get; set; }
        public virtual Devices Devices { get; set; }
    }
}
