//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cloud_Background.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricDevices
    {
        public int IDHistoricDevices { get; set; }
        public int IDDevice { get; set; }
        public System.DateTime HistDeviceDate { get; set; }
        public int IDDeviceAction { get; set; }
        public string HistDeviceIPaddress { get; set; }
        public string HistDeviceAux { get; set; }
    
        public virtual AuxDeviceActions AuxDeviceActions { get; set; }
        public virtual Devices Devices { get; set; }
    }
}
